### ISSUE TITLE
How do I save the commit message to the target branch?

### ISSUE THREAD

**Issue by RyanBreathings** [mtanzi/action-automerge#5]
I want to use a commit message for the source branch.
Can you tell me how to do it?

**Comment by richard-scott** [comment]
Looks like you can't until [this](https://github.com/mtanzi/action-automerge/blob/master/src/index.js#L61) bit changes.

**Comment by richard-scott** [comment]
For now, I've forked this repo and updated it so you can set a custom commit message:

```
      - name: merge
        uses: richard-scott/action-automerger@v1.0.3
        with:
          github_token: ${{ github.token }}
          source: 'master'
          target: 'release'
          message: "${{ github.event.commits[0].message }}"
```
          
https://github.com/marketplace/actions/automerger-action
